apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpha
  name: alpha
spec:
  containers:
  - image: nicolaka/netshoot
    command:
    - ping
    - google.com
    name: netshoot
  - image: k8s.gcr.io/echoserver:1.4
    name: echo
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: beta
  name: beta
spec:
  containers:
  - image: nicolaka/netshoot
    command:
    - ping
    - google.com
    name: netshoot
  - image: k8s.gcr.io/echoserver:1.4
    name: echo
  restartPolicy: OnFailure
